name: Build Image

on:
  schedule:
    - cron: "12 4 * * *"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-crates:
    name: Fetch Crates
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Fetch crates
        uses: docker/build-push-action@v4
        with:
          push: false
          build-args: |
            BASE_IMAGE_TAG=1.89.0-slim-bullseye
          target: cratefetcher
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global

  fetch-src:
    name: Fetch SRC
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Fetch src
        uses: docker/build-push-action@v4
        with:
          push: false
          build-args: |
            BASE_IMAGE_TAG=1.89.0-slim-bullseye
          target: srcfetcher
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global

  rustic-image:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
        include:
          - platform: linux/amd64
            runs-on: ubuntu-latest
          - platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          - platform: linux/arm/v7
            runs-on: ubuntu-24.04-arm
    name: Build Docker Image
    runs-on: ${{ matrix.runs-on }}
    needs:
      - fetch-crates
      - fetch-src
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global
          push: false
          platforms: ${{ matrix.platform }}
          build-args: |
            BASE_IMAGE_TAG=1.89.0-slim-bullseye
